[[tool.mypy.overrides]]
module = [
    "cmk.*",
]
ignore_errors = true

[tool.pylint.'MESSAGES CONTROL']
disable = "missing-docstring"

[tool.pytest.ini_options]
pythonpath = "checkmk/"

[tool.isort]
# black compatibility
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
order_by_type = false
